app/urls.py
from django.urls import path
from . import views

app_name = 'marketing'

urlpatterns = [
    path('', views.store, name="store"),
    path('cart/', views.cart, name="cart"),
    path('add_to_cart/<int:pk>/', views.add_to_cart, name="add"),
    path('sub_from_cart/<int:pk>/', views.sub_from_cart, name="subtract"),  
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls', namespace='marketing')),
    path('users/', include('users.urls', namespace='users')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.sign_in, name='login'),
    path('logout/', views.sign_out, name='logout'),
    path('register/', views.sign_up, name='register'),
]

app/models.py
from django.db import models
from django.contrib.auth.models import User
from shortuuidfield import ShortUUIDField

# Create your models here.

class Product(models.Model):
    name = models.CharField(max_length=25)
    image = models.ImageField()
    price = models.DecimalField(max_digits=9, decimal_places=2)
    date = models.DateTimeField(auto_created=True)

    def __str__(self):
        return self.name

class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField(default=0, null=True)
    transaction_id = ShortUUIDField()
    date_ordered = models.DateTimeField(auto_now_add=True)

    @property
    def total_price(self):
        total = self.product.price * self.quantity
        return total

    def __str__(self):
        return str(self.id)

app/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required
from .models import *

# Create your views here.

def store(request):
    products = Product.objects.all().order_by('-date')
    return render(request, 'index.html', {'products': products})

@login_required(login_url='users:login')
def cart(request):
    orders = Order.objects.filter(user=request.user)
    return render(request, 'cart.html', {'orders': orders})

@login_required(login_url='users:login')
def add_to_cart(request, pk):
    product = get_object_or_404(Product, pk=pk)
    order, created = Order.objects.get_or_create(user=request.user, product=product)
    order.quantity += 1
    order.save()
    return redirect('marketing:cart')
   
@login_required(login_url='users:login')   
def sub_from_cart(request, pk):
    product = get_object_or_404(Product, pk=pk)
    order, created = Order.objects.get_or_create(user=request.user, product=product)
    order.quantity -= 1
    order.save()
    
    if order.quantity <= 0:
        order.delete()
    return redirect('marketing:cart')

users/views.py
from django.shortcuts import redirect, render
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm

# Create your views here.

def sign_in(request):

    username = request.POST.get('username')
    password = request.POST.get('password')
    user = authenticate(request, username=username, password=password)
    
    if user is not None:
        login(request, user)
        return redirect('marketing:store')
    else:
        messages.error(request, 'username or password does not exist!')
    return render(request, 'users/login.html')

def sign_out(request):
    logout(request)
    return redirect('marketing:store')

def sign_up(request):
    form = UserCreationForm()

    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.save()
            login(request, user)
            return redirect('marketing:store')
    else:
        messages.error(request, 'an error occured during registration!')

    return render(request, 'users/register.html', {'form': form})

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Home {% endblock title %} | Shoppin</title>
    {% block head_css %}    
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link href='https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css' rel='stylesheet'>
        {% block head_css_page %}{% endblock head_css_page %}
    {% endblock head_css %}
</head>
<body>
    <!-- Header -->
    <header>
        <!-- Nav -->
        <div class="nav container">
            <a href="{% url 'marketing:store' %}" class="logo">Shoppin</a>
            <a href="{% url 'marketing:cart' %}">
                <i class='bx bx-shopping-bag' id="cart-icon"></i>
                <span class="badge">0</span>
            </a>   
        </div>
    </header>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}

    {% block content %}
        if you're seeing this, something's wrong        
    {% endblock content %}
    <footer>
        <p>Shoppin eCommerce © 2022. All rights reserved</p>
    </footer>
</body>
</html>

templates/cart.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Cart {% endblock title %}
{% block head_css_page %}<link rel="stylesheet" href="{% static 'css/cart.css' %}">{% endblock head_css_page %}
{% block content %}
    <section class="table">
        {% if orders %}
            <table class="cart">
                <thead>
                    <tr>
                        <td>Product</td> 
                        <td>Qty</td>
                        <td>Total</td>
                    </tr>
                </thead>
                {% for order in orders %}
                    <tbody>
                        <tr>
                            <td class="product">
                                <img src="{{order.product.image.url}}" alt="">
                                <div>
                                    <p>{{order.product.name}}</p>
                                    <small>Price: ${{order.product.price}}</small>
                                </div>
                            </td> 
                            <td class="qty">
                                <a href="{% url 'marketing:add' order.product.pk %}">+</a>
                                <small>{{order.quantity}}</small>
                                <a href="{% url 'marketing:subtract' order.product.pk %}">-</a> 
                            </td>
                            <td class="total">${{order.total_price}}</td>
                        </tr>
                    </tbody>
                {% endfor %}
                <tfoot>
                    <tr>
                        <td colspan="2" align="right">Cart Total</td>
                        <td>$</td>
                    </tr>
                </tfoot>
            </table>
        {% else %}
            <div class="empty-cart">
                <img src="{% static 'svg/empty_cart.svg' %}" alt="">
                <h2>Your cart is empty!</h2>
                <p>Browse our categories and discover our best deals!</p>
                <a href="{% url 'marketing:store' %}"><button>Start Shoppin</button></a>
            </div>
        {% endif %}
    </section>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block content %}
    <section class="shop container">
        <h2 class="section-title">Shop Products</h2>
        <!-- Content -->
        <div class="shop-content">
            <!-- Box -->
            {% for product in products %}
            <div class="product-box">
                <img src="{{product.image.url}}" class="product-image" alt="">
                <h2 class="product-title">{{product.name}}</h2>
                <span class="price">${{product.price}}</span>
                <a href="{% url 'marketing:add' product.pk %}">
                    <i title="add to cart" class='bx bx-shopping-bag add-cart'></i>
                </a>
            </div>
            {% endfor %}
        </div>
    </section>
{% endblock %}

templates/users/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Login {% endblock title %}
{% block content %}  
    <style>
        div {
            padding-left: 2rem;
        }
        label, input {
            display: block;
        }
    </style>

    <section>
        <div>
            <form action="" method="post">
                {% csrf_token %}
                <label for="">Username:</label>
                <input type="text" name="username">
    
                <label for="">Password:</label>
                <input type="password" name="password">
    
                <button type="submit" value="login">Sign In</button>

            </form>
            <p>haven't signed up yet?</p>
            <a href="{% url 'users:register' %}">Sign Up</a>
        </div>
    </section>
{% endblock %}

templates/users/register.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Register {% endblock title %}
{% block content %}
    <style>
        div {
            padding-left: 2rem;
        }
        label, input {
            display: block;
        }
    </style>
          
    <section>
        <div>
            <form action="" method="post">
                {% csrf_token %}

                {% for field in form %}
                <label for="">{{field.label}}</label>
                {{field}}
                {% endfor %}
                <button type="submit" value="register">Sign Up</button>
                <p>already signed up?</p>
                <a href="{% url 'users:login' %}">Sign In</a>
            </form>
        </div>
    </section>
{% endblock %}